version: '3.4'

services:
  nginx-ms:
    image: nginx:1-alpine
    volumes: 
      - './nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf'
    ports:
      - '8087:81'
    tty: true
    depends_on:
     - first-ms
     - second-ms

  first-ms:
    container_name: first-ms
    build: ./firstMicroservice/
    volumes:
      - './firstMicroservice/:/src'
      # - './services/ms1/package.json:/usr/src/package.json'
    ports:
      - '8081:8081' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}

  second-ms:
    container_name: second-ms
    build: ./secondMicroservice/
    volumes:
      - './secondMicroservice/:/src'
      #- './utils:/src'
      # - './services/ms2/package.json:/usr/src/package.json'
    ports:
      - '8082:8082' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
  
  frontend:
    container_name: frontend
    build: ./sample-project-frontend/ 

    ports:
      - '4200:4200' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
  

